package Map.Object;

public enum Type {
    BATTLE, DIALOGUE, SHOP, HEAL, SAVE, TELEPORT, QUEST, PUZZLE, CUTSCENE, EVENT, NONE, COLLISION, DOOR, SIGN, ITEM, NPC, PLAYER, ENEMY, OBJECT, TRIGGER, TILE, TILESET, LAYER, MAP, WORLD, GAME
}
